# build.yaml - Build configuration for code generation

targets:
  $default:
    builders:
      drift_dev:
        enabled: true
        options:
          store_date_time_values_as_text: false
          
      freezed:
        enabled: true
        
      json_serializable:
        enabled: true
        
      riverpod_generator:
        enabled: true

      retrofit_generator:
        enabled: true
